set gaSet(sw)          "??"
set gaSet(dbrSW)       ""
set gaSet(swPack)      "SW3712"
set gaSet(dbrBVerSw)   "??"
set gaSet(dbrBVer)     "??"
set gaSet(cpld)        "??"
set gaSet(DutFullName) "ETX-2I-100G_TA/H/ACRF/4Q/16SFPP/PTP"
set gaSet(DutInitName) "ETX-2I-100G_TA.H.ACRF.4Q.16SFPP.PTP.tcl"
set gaSet(BootCF) ""
set gaSet(SWCF) "C:/download/SW/6.8.1(0.36)/sw-pack_2i_100g_4q.bin"
set gaSet(19CF) ""
set gaSet(Half19CF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2-100G-4Q/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(19SyncECF) ""
set gaSet(Half19SyncECF) "c:/aa"
set gaSet(Aux1CF) ""
set gaSet(Aux2CF) ""
set gaSet(DefaultCF) "C:/AT-ETX-2-100G-4Q/ConfFiles/Default_conf/TA_User Default ETX2i-100G_rev2.txt"
set gaSet(licDir) "??"
